[tool.ruff]
line-length = 100
target-version = "py310"

select = [
    "E",   # pycodestyle Style theo PEP8 (error-level)
    "F",   # 	Pyflakes base logic, variables, imports, etc.
    "I",   # isort Import sorting
    "B",   # flake8-bugbear Bugbear plugin for flake8
    "N",   #  pep8-naming Naming conventions
    "C",   # interact with max-complexity
    "SIM", #flake8-simplify Simplify plugin for flake8
    "T",   #flake8-debugger find and remove debugger statements
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.ruff.lint]
ignore = [
    "E501", # Line too long
    # "F401",  # Module imported but unused
    # "F403",  # 'from module import *' used
    # "I001",  # Import block is unsorted
]

fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.mccabe]
max-complexity = 15
